#!/usr/bin/env python3
"""analyze/make_tables.py — generate the paper's result tables FROM the CSVs.

WHY THIS EXISTS
---------------
report/paper_acl.tex carried ~45 measured numbers transcribed by hand across 12
regions, with no \\input of any generated file. That is how it came to claim
"$N=40$ per condition" while report/rq1_causal.csv says wrong_object is n=28 and
openvla/repeated is n=20 — and hand-transcription is the same mechanism that let
fabricated numbers survive review. Every table the paper shows is emitted here
from the CSV instead, so a stale number becomes impossible rather than unlikely.

Writes report/tables/*.tex, each containing ONE tabular environment (no caption,
no label — those stay in paper_acl.tex where they can be edited):

    rq1_causal.tex        wide per-model view, the paper's current shape
    rq1_causal_full.tex   long form: every model x condition with n and 95% CI
    rq1_n_note.tex        one sentence stating the true per-condition n
    rq2_para.tex          paraphrase axes, WITH the n column
    rq3_divergence.tex    kinematic divergence, WITH the n_pairs column

Usage: python analyze/make_tables.py       (CPU only, reads report/*.csv)
"""
from __future__ import annotations

import csv
import math
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
REPORT = REPO_ROOT / "report"
OUT = REPORT / "tables"

PRETTY = {"smolvla": "SmolVLA (0.45B)", "openvla": "OpenVLA (7B)",
          "openvla_oft": "OpenVLA-OFT (7.5B)"}
MODEL_ORDER = ["smolvla", "openvla", "openvla_oft"]
COND_ORDER = ["original", "blank", "nonsense", "wrong_action", "wrong_object",
              "wrong_task", "repeated"]
COND_PRETTY = {"original": "Baseline", "blank": "Blank", "nonsense": "Nonsense",
               "wrong_action": "Wrong Action", "wrong_object": "Wrong Object",
               "wrong_task": "Wrong Task", "repeated": "Repeated"}


def wilson(k: int, n: int, z: float = 1.96) -> tuple[float, float]:
    """Wilson score interval for a proportion.

    Deliberately not the normal approximation: at these cell sizes the headline
    wrong_object rate is 1 success in 14, where a Wald interval runs off the end of
    [0,1] and understates the uncertainty. Wilson stays inside the unit interval
    and is honest about small n, which is the entire point of reporting it.
    """
    if n == 0:
        return (float("nan"), float("nan"))
    p = k / n
    d = 1 + z * z / n
    centre = (p + z * z / (2 * n)) / d
    half = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return (max(0.0, centre - half), min(1.0, centre + half))


def read_csv(name: str) -> list[dict]:
    path = REPORT / name
    if not path.exists():
        print(f"[make_tables] SKIP: {path} not found", file=sys.stderr)
        return []
    with open(path) as f:
        return list(csv.DictReader(f))


def fnum(s, default=None):
    try:
        return float(s)
    except (TypeError, ValueError):
        return default


def pct(x, nd=1):
    return "--" if x is None else f"{100 * x:.{nd}f}\\%"


def write(name: str, body: str) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / name).write_text(
        "% GENERATED by analyze/make_tables.py — do not edit by hand.\n"
        "% Re-run after any change to report/*.csv.\n" + body
    )
    print(f"[make_tables] wrote {(OUT / name).relative_to(REPO_ROOT)}")


def rq1_tables(rows: list[dict]) -> None:
    if not rows:
        return
    by = {(r["model"], r["condition"]): r for r in rows}

    # --- wide view: the shape the paper already uses -------------------------
    lines = [r"\begin{tabular}{l" + "c" * len(COND_ORDER) + "}", r"\toprule",
             r"\textbf{Model} & " +
             " & ".join(rf"\textbf{{{COND_PRETTY[c]}}}" for c in COND_ORDER) + r" \\",
             r"\midrule"]
    for m in MODEL_ORDER:
        cells = []
        for c in COND_ORDER:
            r = by.get((m, c))
            if not r:
                cells.append("--")
                continue
            tsr, std, css = fnum(r["TSR"]), fnum(r["TSR_std_over_seeds"]), fnum(r["CSS"])
            cell = pct(tsr)
            if std:  # only when seeds actually disagree; std=0 adds nothing
                cell += rf"$\pm${100 * std:.1f}"
            if css is not None:
                cell += f" ({css:.2f})"
            cells.append(cell)
        lines.append(f"{PRETTY[m]} & " + " & ".join(cells) + r" \\")
    # n per condition, pooled over seeds. Show every distinct value when the models
    # disagree (openvla/repeated is seed-7 only, n=20, while the others are 40) —
    # collapsing to one number here is how "N=40 per condition" got into the paper.
    n_cells = []
    for c in COND_ORDER:
        ns = sorted({int(fnum(by[(m, c)]["n_total"], 0)) for m in MODEL_ORDER if (m, c) in by})
        n_cells.append("/".join(str(n) for n in ns) if ns else "--")
    lines += [r"\midrule",
              r"\textit{episodes per cell} & " + " & ".join(n_cells) + r" \\",
              r"\bottomrule", r"\end{tabular}"]
    write("rq1_causal.tex", "\n".join(lines) + "\n")

    # --- long view: n and a CI for every cell, which the wide view cannot fit -
    lines = [r"\begin{tabular}{llrcc}", r"\toprule",
             r"\textbf{Model} & \textbf{Condition} & \textbf{$n$} & "
             r"\textbf{TSR (95\% CI)} & \textbf{CSS} \\", r"\midrule"]
    for i, m in enumerate(MODEL_ORDER):
        if i:
            lines.append(r"\midrule")
        for c in COND_ORDER:
            r = by.get((m, c))
            if not r:
                continue
            n = int(fnum(r["n_total"], 0))
            tsr = fnum(r["TSR"])
            css = fnum(r["CSS"])
            lo, hi = wilson(round(tsr * n), n) if (tsr is not None and n) else (None, None)
            ci = "--" if lo is None else f"[{100 * lo:.1f}, {100 * hi:.1f}]"
            lines.append(f"{PRETTY[m]} & \\texttt{{{c.replace('_', chr(92) + '_')}}} & {n} & "
                         f"{pct(tsr)} {ci} & {'--' if css is None else f'{css:.2f}'} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write("rq1_causal_full.tex", "\n".join(lines) + "\n")

    # --- the note that replaces the false "N=40 per condition" ---------------
    counts = {}
    for c in COND_ORDER:
        ns = {int(fnum(by[(m, c)]["n_total"], 0)) for m in MODEL_ORDER if (m, c) in by}
        counts[c] = ns
    parts = []
    for c in COND_ORDER:
        ns = counts[c]
        parts.append(rf"\texttt{{{c.replace('_', chr(92) + '_')}}} $n={'/'.join(str(n) for n in sorted(ns))}$")
    seeds = sorted({s for r in rows for s in r["seeds"].split(";")})
    write("rq1_n_note.tex",
          "Episode counts differ by condition and model, so there is no single $N$: " +
          ", ".join(parts) + rf". Seeds {', '.join(seeds)}." + "\n")


def rq2_table(rows: list[dict]) -> None:
    if not rows:
        return
    axis_pretty = {"para_object": "Object", "para_action": "Action",
                   "para_compositional": "Compositional", "ALL": r"\textbf{All axes}"}
    # `scenes` is not decoration: SmolVLA's 2963 compositional episodes cover only 20
    # distinct initial scenes, so n badly overstates the independent variation behind
    # the estimate. The paper says it reports scenes alongside n, so the table must.
    lines = [r"\begin{tabular}{llrrccc}", r"\toprule",
             r"\textbf{Model} & \textbf{Paraphrase Axis} & \textbf{$n$} & "
             r"\textbf{scenes} & \textbf{TSR} & "
             r"\textbf{$\Delta$TSR (pp)} & \textbf{PRIDE} \\", r"\midrule"]
    for i, m in enumerate(MODEL_ORDER):
        mr = [r for r in rows if r["model"] == m]
        if not mr:
            continue
        if i:
            lines.append(r"\midrule")
        for r in mr:
            scenes = fnum(r.get("n_scenes"))
            lines.append(
                f"{PRETTY[m]} & {axis_pretty.get(r['axis'], r['axis'])} & {int(fnum(r['n'], 0))} & "
                f"{'--' if scenes is None else int(scenes)} & "
                f"{pct(fnum(r['TSR']), 2)} & $-{fnum(r['delta_TSR_pp'], 0):.2f}$ & "
                f"{fnum(r['PRIDE'], 0):.1f} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write("rq2_para.tex", "\n".join(lines) + "\n")


def rq3_table(rows: list[dict]) -> None:
    if not rows:
        return
    lines = [r"\begin{tabular}{llrcc}", r"\toprule",
             r"\textbf{Model} & \textbf{Condition} & \textbf{pairs} & "
             r"\textbf{$t_{\text{div}}$ (samples)} & \textbf{$e(T)$ [m]} \\", r"\midrule"]
    for m in MODEL_ORDER:
        for r in [x for x in rows if x["model"] == m]:
            cond = r["condition"].replace("_", chr(92) + "_")
            lines.append(
                f"{PRETTY[m]} & \\texttt{{{cond}}} & {int(fnum(r['n_pairs'], 0))} & "
                f"{fnum(r['mean_tdiv_step'], 0):.2f} & {fnum(r['final_error_m'], 0):.4f} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write("rq3_divergence.tex", "\n".join(lines) + "\n")


def wordclass_table(rows: list[dict]) -> None:
    """The antonym vs near-synonym split behind the RQ2 reframe.

    This was hand-written into paper_acl.tex. Those five numbers move whenever the
    grid is regenerated, and hand-transcribed numbers are exactly what produced this
    project's earlier false claims -- so they are generated here instead, with n in
    the table. Rows come from analyze/instruction_information.py.
    """
    split = [r for r in rows if r["section"] == "wrong_action_split"]
    if not split:
        return
    by = {(r["model"], r["subset"]): r for r in split}
    lines = [r"\begin{tabular}{lcccc}", r"\toprule",
             r"\textbf{Model} & \multicolumn{2}{c}{\textbf{antonym}} & "
             r"\multicolumn{2}{c}{\textbf{near-synonym}} \\",
             r"\cmidrule(lr){2-3} \cmidrule(lr){4-5}",
             r" & $\Delta$TSR & $n$ & $\Delta$TSR & $n$ \\", r"\midrule"]
    for m in MODEL_ORDER:
        cells = []
        for subset in ("antonym", "near-syn"):
            r = by.get((m, subset))
            if r is None:
                cells += ["--", "--"]
                continue
            # note field carries "orig=<rate> delta_pp=<pp>"; delta is a drop.
            delta = None
            for tok in (r.get("note") or "").split():
                if tok.startswith("delta_pp="):
                    delta = fnum(tok.split("=", 1)[1])
            n = int(fnum(r["n"], 0))
            if delta is None:
                cells += ["--", str(n)]
            elif abs(delta) < 0.05:  # avoid rendering a signed "-0.0"
                cells += [r"\phantom{$-$}$0.0$ pp", str(n)]
            else:
                cells += [f"$-{delta:.1f}$ pp", str(n)]
        lines.append(f"{PRETTY[m]} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write("rq2_wordclass.tex", "\n".join(lines) + "\n")


def main() -> None:
    rq1_tables(read_csv("rq1_causal.csv"))
    rq2_table(read_csv("rq2_paraphrase.csv"))
    rq3_table(read_csv("rq3_divergence.csv"))
    wordclass_table(read_csv("instruction_information.csv"))
    print("\n[make_tables] done. In paper_acl.tex, replace each hand-written tabular with:\n"
          "    \\input{tables/rq1_causal}      (and rq1_n_note in the caption)\n"
          "    \\input{tables/rq2_para}\n"
          "    \\input{tables/rq3_divergence}")


if __name__ == "__main__":
    main()
